### ISSUE TITLE
hitting f5 hard enough panics

### ISSUE THREAD

**Issue by matti** [benjaminhr/redis-analytics#3]
rallytics_1    | panic: concurrent write to websocket connection
rallytics_1    |
rallytics_1    | goroutine 7 [running]:
rallytics_1    | github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00011be90, 0xc00026aa01, 0xc00026aa5a, 0x0, 0x6, 0x8, 0xc00026aa58)
rallytics_1    | 	/go/src/github.com/gorilla/websocket/conn.go:610 +0x612
rallytics_1    | github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0002e91e0, 0x1, 0xc00026aa58, 0x2, 0x8, 0x8, 0xc0004480a0)
rallytics_1    | 	/go/src/github.com/gorilla/websocket/conn.go:763 +0x23d
rallytics_1    | main.broadcast()
rallytics_1    | 	/go/main.go:95 +0xf0
rallytics_1    | main.pollRedis()
rallytics_1    | 	/go/main.go:60 +0x127
rallytics_1    | created by main.main
rallytics_1    | 	/go/main.go:43 +0x1ad

**Comment by matti** [comment]
it's because of
```
				wClient.Close()
				delete(clients, wClient)
```
?
